const heroVideos=[...document.querySelectorAll('.hero-video')];let activeVideo=0;
function playNext(){heroVideos[activeVideo].classList.remove('is-active');activeVideo=(activeVideo+1)%heroVideos.length;const next=heroVideos[activeVideo];next.currentTime=0;next.classList.add('is-active');next.play().catch(()=>{});}
heroVideos.forEach(video=>video.addEventListener('ended',playNext));
const soundButton=document.querySelector('.sound');soundButton.addEventListener('click',()=>{const current=heroVideos[activeVideo];current.muted=!current.muted;heroVideos.forEach((v,i)=>{if(i!==activeVideo)v.muted=true});soundButton.innerHTML=`<i></i> Sound ${current.muted?'off':'on'}`;});
const dialog=document.querySelector('.case-dialog');const caseData={measure:['CASE 01','Measure Yourself','Продуктовый концепт, в котором повседневный аксессуар превращается в измерительный инструмент и визуальный statement.','assets/work-02.jpg'],headwear:['CASE 02','Obladaet / Headwear','Исследование формы, типографики и фактуры в серии цифровых аксессуаров.','assets/work-01.jpg'],dark:['CASE 03','Dark Matter','Монохромное исследование материала и света для fashion-продукта.','assets/work-03.jpg'],motion:['CASE 04','Visual Experiments','Серия коротких motion-экспериментов, созданных для вертикальных digital-платформ.','assets/work-04.jpg']};
document.querySelectorAll('.case-open').forEach(button=>button.addEventListener('click',()=>{const data=caseData[button.dataset.case];dialog.querySelector('.dialog-number').textContent=data[0];dialog.querySelector('h2').textContent=data[1];dialog.querySelector('p').textContent=data[2];dialog.querySelector('img').src=data[3];dialog.showModal();}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.animate([{opacity:0,transform:'translateY(35px)'},{opacity:1,transform:'none'}],{duration:700,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'});}),{threshold:.08});
document.querySelectorAll('.project,.statement,.about-intro,.reel').forEach(el=>observer.observe(el));
